






















#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;




namespace SymDemo.Common.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }		

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	    [SitecoreInfo(SitecoreInfoType.Url)]
        string Url { get; }
	
        [SitecoreInfo(SitecoreInfoType.TemplateId)]
        Guid TemplateId { get; }       
	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}		

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }

		[SitecoreInfo(SitecoreInfoType.TemplateId)]
        public virtual Guid TemplateId { get; private set; }
	}
}
namespace SymDemo.Common.Models.Items
{


 	/// <summary>
	/// IPage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/SymDemo/Common/Page</para>	
	/// <para>ID: 3fd92b84-4273-4a0d-b30b-2c824d44d760</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPageConstants.TemplateIdString, Cachable=false)]
	public partial interface IPage : IGlassBase , Items.ITitledComponent
	{

					/// <summary>
					/// The Description field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: e4c7af10-b316-4af1-976a-06a433b0a32a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPageConstants.DescriptionFieldName)]
					string Description  {get; set;}
			

					/// <summary>
					/// The MetaTags field.
					/// <para></para>
					/// <para>Field Type: Name Value List</para>		
					/// <para>Field ID: 2cc0d26f-76a1-4a78-9761-c59bfa8213e1</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPageConstants.MetaTagsFieldName)]
					System.Collections.Specialized.NameValueCollection MetaTags  {get; set;}
			

					/// <summary>
					/// The Robots field.
					/// <para></para>
					/// <para>Field Type: Droplist</para>		
					/// <para>Field ID: e2c18465-49e1-4f77-82f8-0ea5843dd31f</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IPageConstants.RobotsFieldName)]
					string Robots  {get; set;}
			

	}


	public static partial class IPageConstants{

			public const string TemplateIdString = "3fd92b84-4273-4a0d-b30b-2c824d44d760";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Page";


			
			public static readonly ID DescriptionFieldId = new ID("e4c7af10-b316-4af1-976a-06a433b0a32a");
			public const string DescriptionFieldName = "Description";
			

			
			public static readonly ID MetaTagsFieldId = new ID("2cc0d26f-76a1-4a78-9761-c59bfa8213e1");
			public const string MetaTagsFieldName = "MetaTags";
			

			
			public static readonly ID RobotsFieldId = new ID("e2c18465-49e1-4f77-82f8-0ea5843dd31f");
			public const string RobotsFieldName = "Robots";
			

			
			public static readonly ID TitleFieldId = new ID("5d6b32bd-02c7-4f95-9bce-c487d398699a");
			public const string TitleFieldName = "Title";
			
	

	}

	
	/// <summary>
	/// Page
	/// <para></para>
	/// <para>Path: /sitecore/templates/SymDemo/Common/Page</para>	
	/// <para>ID: 3fd92b84-4273-4a0d-b30b-2c824d44d760</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPageConstants.TemplateIdString, Cachable=false)] 
	public partial class Page  : GlassBase, IPage 
	{
	   

				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: e4c7af10-b316-4af1-976a-06a433b0a32a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					

				/// <summary>
				/// The MetaTags field.
				/// <para></para>
				/// <para>Field Type: Name Value List</para>		
				/// <para>Field ID: 2cc0d26f-76a1-4a78-9761-c59bfa8213e1</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.MetaTagsFieldName)]
				public virtual System.Collections.Specialized.NameValueCollection MetaTags  {get; set;}
					

				/// <summary>
				/// The Robots field.
				/// <para></para>
				/// <para>Field Type: Droplist</para>		
				/// <para>Field ID: e2c18465-49e1-4f77-82f8-0ea5843dd31f</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.RobotsFieldName)]
				public virtual string Robots  {get; set;}
					

				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 5d6b32bd-02c7-4f95-9bce-c487d398699a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IPageConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
	
	}

}
namespace SymDemo.Common.Models.Items
{


 	/// <summary>
	/// IItem Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/SymDemo/Common/Item</para>	
	/// <para>ID: 52a71948-4930-479c-9b65-e4300f50502f</para>	
	/// </summary>
	[SitecoreType(TemplateId=IItemConstants.TemplateIdString, Cachable=false)]
	public partial interface IItem : IGlassBase 
	{

					/// <summary>
					/// The Value field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 8c0de2f9-0546-4040-9f93-7ce3cc7ed23a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IItemConstants.ValueFieldName)]
					string Value  {get; set;}
			

	}


	public static partial class IItemConstants{

			public const string TemplateIdString = "52a71948-4930-479c-9b65-e4300f50502f";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Item";


			
			public static readonly ID ValueFieldId = new ID("8c0de2f9-0546-4040-9f93-7ce3cc7ed23a");
			public const string ValueFieldName = "Value";
			
	

	}

	
	/// <summary>
	/// Item
	/// <para></para>
	/// <para>Path: /sitecore/templates/SymDemo/Common/Item</para>	
	/// <para>ID: 52a71948-4930-479c-9b65-e4300f50502f</para>	
	/// </summary>
	[SitecoreType(TemplateId=IItemConstants.TemplateIdString, Cachable=false)] 
	public partial class Item  : GlassBase, IItem 
	{
	   

				/// <summary>
				/// The Value field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 8c0de2f9-0546-4040-9f93-7ce3cc7ed23a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IItemConstants.ValueFieldName)]
				public virtual string Value  {get; set;}
					
	
	}

}
namespace SymDemo.Common.Models.Items
{


 	/// <summary>
	/// ITitledComponent Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/SymDemo/Common/TitledComponent</para>	
	/// <para>ID: 9a18bc44-effa-467a-9668-63f42670acb9</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITitledComponentConstants.TemplateIdString, Cachable=false)]
	public partial interface ITitledComponent : IGlassBase 
	{

					/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 5d6b32bd-02c7-4f95-9bce-c487d398699a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ITitledComponentConstants.TitleFieldName)]
					string Title  {get; set;}
			

	}


	public static partial class ITitledComponentConstants{

			public const string TemplateIdString = "9a18bc44-effa-467a-9668-63f42670acb9";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "TitledComponent";


			
			public static readonly ID TitleFieldId = new ID("5d6b32bd-02c7-4f95-9bce-c487d398699a");
			public const string TitleFieldName = "Title";
			
	

	}

	
	/// <summary>
	/// TitledComponent
	/// <para></para>
	/// <para>Path: /sitecore/templates/SymDemo/Common/TitledComponent</para>	
	/// <para>ID: 9a18bc44-effa-467a-9668-63f42670acb9</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITitledComponentConstants.TemplateIdString, Cachable=false)] 
	public partial class TitledComponent  : GlassBase, ITitledComponent 
	{
	   

				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 5d6b32bd-02c7-4f95-9bce-c487d398699a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ITitledComponentConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
	
	}

}
namespace SymDemo.Common.Models.Items
{


 	/// <summary>
	/// ISite Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/SymDemo/Common/Site</para>	
	/// <para>ID: a3d3c012-0250-4d86-a75f-52f3c23d6aa5</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteConstants.TemplateIdString, Cachable=false)]
	public partial interface ISite : IGlassBase , Items.ITitledComponent
	{

	}


	public static partial class ISiteConstants{

			public const string TemplateIdString = "a3d3c012-0250-4d86-a75f-52f3c23d6aa5";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Site";


			
			public static readonly ID TitleFieldId = new ID("5d6b32bd-02c7-4f95-9bce-c487d398699a");
			public const string TitleFieldName = "Title";
			
	

	}

	
	/// <summary>
	/// Site
	/// <para></para>
	/// <para>Path: /sitecore/templates/SymDemo/Common/Site</para>	
	/// <para>ID: a3d3c012-0250-4d86-a75f-52f3c23d6aa5</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteConstants.TemplateIdString, Cachable=false)] 
	public partial class Site  : GlassBase, ISite 
	{
	   

				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 5d6b32bd-02c7-4f95-9bce-c487d398699a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
	
	}

}
namespace SymDemo.Common.Models.Items
{


 	/// <summary>
	/// IComponents Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/SymDemo/Common/Components</para>	
	/// <para>ID: ab04e291-4634-40bd-8d27-a4f36147ab63</para>	
	/// </summary>
	[SitecoreType(TemplateId=IComponentsConstants.TemplateIdString, Cachable=false)]
	public partial interface IComponents : IGlassBase 
	{

	}


	public static partial class IComponentsConstants{

			public const string TemplateIdString = "ab04e291-4634-40bd-8d27-a4f36147ab63";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Components";

	

	}

	
	/// <summary>
	/// Components
	/// <para></para>
	/// <para>Path: /sitecore/templates/SymDemo/Common/Components</para>	
	/// <para>ID: ab04e291-4634-40bd-8d27-a4f36147ab63</para>	
	/// </summary>
	[SitecoreType(TemplateId=IComponentsConstants.TemplateIdString, Cachable=false)] 
	public partial class Components  : GlassBase, IComponents 
	{
	   
	
	}

}
