






















#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;
using SymDemo.Common.Models;


namespace SymDemo.Site.Models.Items
{


 	/// <summary>
	/// IScrollSource Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/SymDemo/DemoSite/ScrollSource</para>	
	/// <para>ID: 74b86b0c-87f0-4157-be9c-b6792d494bb5</para>	
	/// </summary>
	[SitecoreType(TemplateId=IScrollSourceConstants.TemplateIdString, Cachable=false)]
	public partial interface IScrollSource : IGlassBase 
	{

					/// <summary>
					/// The Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 2f5f0dbe-c1a8-4934-a867-e3bf9124742a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IScrollSourceConstants.ImageFieldName)]
					Image Image  {get; set;}
			

					/// <summary>
					/// The Intro field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: ec3e21e0-9b43-41bb-a1d8-95a5df85d056</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IScrollSourceConstants.IntroFieldName)]
					string Intro  {get; set;}
			

					/// <summary>
					/// The Text field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: d251cc9c-40ec-4fbf-b331-e95649923be7</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IScrollSourceConstants.TextFieldName)]
					string Text  {get; set;}
			

	}


	public static partial class IScrollSourceConstants{

			public const string TemplateIdString = "74b86b0c-87f0-4157-be9c-b6792d494bb5";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "ScrollSource";


			
			public static readonly ID ImageFieldId = new ID("2f5f0dbe-c1a8-4934-a867-e3bf9124742a");
			public const string ImageFieldName = "Image";
			

			
			public static readonly ID IntroFieldId = new ID("ec3e21e0-9b43-41bb-a1d8-95a5df85d056");
			public const string IntroFieldName = "Intro";
			

			
			public static readonly ID TextFieldId = new ID("d251cc9c-40ec-4fbf-b331-e95649923be7");
			public const string TextFieldName = "Text";
			
	

	}

	
	/// <summary>
	/// ScrollSource
	/// <para></para>
	/// <para>Path: /sitecore/templates/SymDemo/DemoSite/ScrollSource</para>	
	/// <para>ID: 74b86b0c-87f0-4157-be9c-b6792d494bb5</para>	
	/// </summary>
	[SitecoreType(TemplateId=IScrollSourceConstants.TemplateIdString, Cachable=false)] 
	public partial class ScrollSource  : GlassBase, IScrollSource 
	{
	   

				/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 2f5f0dbe-c1a8-4934-a867-e3bf9124742a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IScrollSourceConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					

				/// <summary>
				/// The Intro field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: ec3e21e0-9b43-41bb-a1d8-95a5df85d056</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IScrollSourceConstants.IntroFieldName)]
				public virtual string Intro  {get; set;}
					

				/// <summary>
				/// The Text field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: d251cc9c-40ec-4fbf-b331-e95649923be7</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IScrollSourceConstants.TextFieldName)]
				public virtual string Text  {get; set;}
					
	
	}

}
